
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Jul 14 18:12:39 CEST 2017
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PIPE = 11;
  public static final int CO = 7;
  public static final int CM = 4;
  public static final int S = 2;
  public static final int RO = 5;
  public static final int NAME = 19;
  public static final int M = 16;
  public static final int CC = 8;
  public static final int NUM = 21;
  public static final int MS = 17;
  public static final int RC = 6;
  public static final int EOF = 0;
  public static final int C = 3;
  public static final int SEP = 12;
  public static final int PRINT = 18;
  public static final int error = 1;
  public static final int ARROW = 10;
  public static final int TOKEN3 = 15;
  public static final int TOKEN2 = 14;
  public static final int EQ = 9;
  public static final int TOKEN1 = 13;
  public static final int PART = 20;
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[11]=new String("PIPE");
		TT[7]=new String("CO");
		TT[4]=new String("CM");
		TT[2]=new String("S");
		TT[5]=new String("RO");
		TT[19]=new String("NAME");
		TT[16]=new String("M");
		TT[8]=new String("CC");
		TT[21]=new String("NUM");
		TT[17]=new String("MS");
		TT[6]=new String("RC");
		TT[0]=new String("EOF");
		TT[3]=new String("C");
		TT[12]=new String("SEP");
		TT[18]=new String("PRINT");
		TT[1]=new String("error");
		TT[10]=new String("ARROW");
		TT[15]=new String("TOKEN3");
		TT[14]=new String("TOKEN2");
		TT[9]=new String("EQ");
		TT[13]=new String("TOKEN1");
		TT[20]=new String("PART");
	}
public String getTT(int i){return TT[i];}
}
