
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Jun 23 11:44:57 CEST 2017
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RO = 6;
  public static final int ISTR = 4;
  public static final int CM = 5;
  public static final int VARIABLE = 9;
  public static final int ATOM = 8;
  public static final int EOF = 0;
  public static final int REND = 3;
  public static final int RC = 7;
  public static final int DOT = 2;
  public static final int error = 1;
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[6]=new String("RO");
		TT[4]=new String("ISTR");
		TT[5]=new String("CM");
		TT[9]=new String("VARIABLE");
		TT[8]=new String("ATOM");
		TT[0]=new String("EOF");
		TT[3]=new String("REND");
		TT[7]=new String("RC");
		TT[2]=new String("DOT");
		TT[1]=new String("error");
	}
public String getTT(int i){return TT[i];}
}
