
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jul 11 11:07:58 CEST 2017
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 24;
  public static final int DOUBLE_TYPE = 5;
  public static final int ELSE = 7;
  public static final int PLUS = 19;
  public static final int CO = 15;
  public static final int MAJ = 26;
  public static final int OR = 25;
  public static final int CM = 17;
  public static final int WHILE = 8;
  public static final int S = 18;
  public static final int RO = 11;
  public static final int NOT = 23;
  public static final int IF = 6;
  public static final int CC = 16;
  public static final int ID = 10;
  public static final int RC = 12;
  public static final int SO = 13;
  public static final int EOF = 0;
  public static final int DOUBLE_N = 3;
  public static final int DIV = 21;
  public static final int MINUS = 20;
  public static final int PRINT = 9;
  public static final int error = 1;
  public static final int INT_TYPE = 4;
  public static final int EQ = 28;
  public static final int MIN = 27;
  public static final int INT_N = 2;
  public static final int SC = 14;
  public static final int MUL = 22;
  public static final int UMINUS = 29;
}
