
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Jul 14 14:34:51 CEST 2017
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUM = 13;
  public static final int HEADER2 = 7;
  public static final int C = 5;
  public static final int HEADER1 = 6;
  public static final int IP = 15;
  public static final int DATE = 11;
  public static final int HOUR = 12;
  public static final int TIMEH = 9;
  public static final int DATEH = 8;
  public static final int CM = 2;
  public static final int S = 4;
  public static final int EOF = 0;
  public static final int DOT = 3;
  public static final int error = 1;
  public static final int KBS = 10;
  public static final int NAME = 14;
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[13]=new String("NUM");
		TT[7]=new String("HEADER2");
		TT[5]=new String("C");
		TT[6]=new String("HEADER1");
		TT[15]=new String("IP");
		TT[11]=new String("DATE");
		TT[12]=new String("HOUR");
		TT[9]=new String("TIMEH");
		TT[8]=new String("DATEH");
		TT[2]=new String("CM");
		TT[4]=new String("S");
		TT[0]=new String("EOF");
		TT[3]=new String("DOT");
		TT[1]=new String("error");
		TT[10]=new String("KBS");
		TT[14]=new String("NAME");
	}
public String getTT(int i){return TT[i];}
}
