
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jul 18 14:56:06 CEST 2017
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 20;
  public static final int INCREASE = 17;
  public static final int VAR_QT = 27;
  public static final int OR = 21;
  public static final int CM = 10;
  public static final int DATE = 4;
  public static final int S = 5;
  public static final int RO = 8;
  public static final int NOT = 22;
  public static final int UREAL = 29;
  public static final int TRUE = 23;
  public static final int HASH = 11;
  public static final int RC = 9;
  public static final int WATER = 25;
  public static final int EOF = 0;
  public static final int C = 7;
  public static final int SET = 14;
  public static final int DECREASE = 18;
  public static final int FALSE = 24;
  public static final int SEP = 2;
  public static final int AVG = 19;
  public static final int error = 1;
  public static final int ARROW = 12;
  public static final int OPER = 28;
  public static final int DASH = 13;
  public static final int STATE_CHANGE2 = 16;
  public static final int TOKEN = 3;
  public static final int STATE_CHANGE1 = 15;
  public static final int QM = 6;
  public static final int POWER = 26;
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[20]=new String("AND");
		TT[17]=new String("INCREASE");
		TT[27]=new String("VAR_QT");
		TT[21]=new String("OR");
		TT[10]=new String("CM");
		TT[4]=new String("DATE");
		TT[5]=new String("S");
		TT[8]=new String("RO");
		TT[22]=new String("NOT");
		TT[29]=new String("UREAL");
		TT[23]=new String("TRUE");
		TT[11]=new String("HASH");
		TT[9]=new String("RC");
		TT[25]=new String("WATER");
		TT[0]=new String("EOF");
		TT[7]=new String("C");
		TT[14]=new String("SET");
		TT[18]=new String("DECREASE");
		TT[24]=new String("FALSE");
		TT[2]=new String("SEP");
		TT[19]=new String("AVG");
		TT[1]=new String("error");
		TT[12]=new String("ARROW");
		TT[28]=new String("OPER");
		TT[13]=new String("DASH");
		TT[16]=new String("STATE_CHANGE2");
		TT[3]=new String("TOKEN");
		TT[15]=new String("STATE_CHANGE1");
		TT[6]=new String("QM");
		TT[26]=new String("POWER");
	}
public String getTT(int i){return TT[i];}
}
