
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jul 17 17:18:03 CEST 2017
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ELSE = 13;
  public static final int PLUS = 15;
  public static final int CO = 9;
  public static final int INT = 24;
  public static final int MAJ = 19;
  public static final int CM = 2;
  public static final int S = 4;
  public static final int RO = 7;
  public static final int IF = 12;
  public static final int CC = 10;
  public static final int ID = 22;
  public static final int RC = 8;
  public static final int TYPE = 23;
  public static final int FLOAT = 25;
  public static final int HWORD = 11;
  public static final int EOF = 0;
  public static final int C = 5;
  public static final int DIV = 18;
  public static final int SEP = 6;
  public static final int MINUS = 16;
  public static final int PRINT = 14;
  public static final int error = 1;
  public static final int DOT = 3;
  public static final int EQ = 21;
  public static final int MIN = 20;
  public static final int MUL = 17;
  public static final int UMINUS = 26;
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[13]=new String("ELSE");
		TT[15]=new String("PLUS");
		TT[9]=new String("CO");
		TT[24]=new String("INT");
		TT[19]=new String("MAJ");
		TT[2]=new String("CM");
		TT[4]=new String("S");
		TT[7]=new String("RO");
		TT[12]=new String("IF");
		TT[10]=new String("CC");
		TT[22]=new String("ID");
		TT[8]=new String("RC");
		TT[23]=new String("TYPE");
		TT[25]=new String("FLOAT");
		TT[11]=new String("HWORD");
		TT[0]=new String("EOF");
		TT[5]=new String("C");
		TT[18]=new String("DIV");
		TT[6]=new String("SEP");
		TT[16]=new String("MINUS");
		TT[14]=new String("PRINT");
		TT[1]=new String("error");
		TT[3]=new String("DOT");
		TT[21]=new String("EQ");
		TT[20]=new String("MIN");
		TT[17]=new String("MUL");
		TT[26]=new String("UMINUS");
	}
public String getTT(int i){return TT[i];}
}
